/*
 * This file was generated by the Gradle 'init' task.

plugins {
    application
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("io.hexlet.example.App")
}
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 * This project uses @Incubating APIs which are subject to change.
 */
